"""audit event actor + business + request id

Revision ID: 02a42e24f8cd
Revises: cc70b95bb129
Create Date: 2026-05-24 18:57:28.258997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02a42e24f8cd'
down_revision: Union[str, Sequence[str], None] = 'cc70b95bb129'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('actor_user_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('actor_display_name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('request_id', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_audit_events_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_business_id'), ['business_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_business_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_actor_user_id'))
        batch_op.drop_column('request_id')
        batch_op.drop_column('actor_display_name')
        batch_op.drop_column('actor_user_id')
        batch_op.drop_column('business_id')

    # ### end Alembic commands ###
