"""baseline schema

Revision ID: 15d9df38c0b3
Revises: 
Create Date: 2026-05-24 15:19:11.186007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15d9df38c0b3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_categories',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_entity_type'), ['entity_type'], unique=False)

    op.create_table('tenants',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenants_slug'), ['slug'], unique=True)

    op.create_table('transactions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('raw_description', sa.String(length=512), nullable=False),
    sa.Column('normalized_description', sa.String(length=512), nullable=False),
    sa.Column('merchant', sa.String(length=256), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('businesses',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('industry', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'slug', name='uq_businesses_tenant_slug')
    )
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_businesses_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_businesses_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('categorization_results',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('transaction_id', sa.String(length=32), nullable=False),
    sa.Column('predicted_category_code', sa.String(length=16), nullable=False),
    sa.Column('predicted_category_name', sa.String(length=128), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('explanation', sa.String(length=2048), nullable=False),
    sa.Column('alternative_category_code', sa.String(length=16), nullable=True),
    sa.Column('model_provider', sa.String(length=32), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('AUTO_APPROVED', 'NEEDS_REVIEW', 'UNCATEGORIZABLE', 'CORRECTED', 'REJECTED', 'FAILED', 'ACCOUNTANT_REVIEW_REQUIRED', name='result_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categorization_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categorization_results_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('memberships',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'ACCOUNTANT', 'REVIEWER', 'VIEWER', name='membership_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tenant_id', name='uq_memberships_user_tenant')
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memberships_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('category_mapping_profiles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'name', name='uq_category_mapping_profiles_business_name')
    )
    with op.batch_alter_table('category_mapping_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_mapping_profiles_business_id'), ['business_id'], unique=False)

    op.create_table('review_decisions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('transaction_id', sa.String(length=32), nullable=False),
    sa.Column('categorization_result_id', sa.String(length=32), nullable=False),
    sa.Column('reviewer_action', sa.Enum('APPROVE', 'CORRECT', 'MARK_UNCATEGORIZABLE', 'MARK_FOR_ACCOUNTANT_REVIEW', name='reviewer_action'), nullable=False),
    sa.Column('selected_category_code', sa.String(length=16), nullable=True),
    sa.Column('reviewer_note', sa.String(length=1024), nullable=True),
    sa.Column('owner_question_key', sa.String(length=64), nullable=True),
    sa.Column('owner_question_text', sa.String(length=256), nullable=True),
    sa.Column('owner_answer_label', sa.String(length=128), nullable=True),
    sa.Column('owner_note', sa.String(length=1024), nullable=True),
    sa.Column('suggested_resolution', sa.String(length=64), nullable=True),
    sa.Column('accountant_follow_up_required', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['categorization_result_id'], ['categorization_results.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_decisions_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('category_mapping_entries',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('profile_id', sa.String(length=32), nullable=False),
    sa.Column('intent', sa.String(length=64), nullable=False),
    sa.Column('category_code', sa.String(length=16), nullable=False),
    sa.Column('category_name', sa.String(length=128), nullable=True),
    sa.Column('block_fallback', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['category_mapping_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'intent', name='uq_category_mapping_entries_profile_intent')
    )
    with op.batch_alter_table('category_mapping_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_mapping_entries_profile_id'), ['profile_id'], unique=False)

    op.create_table('correction_memory',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('merchant_key', sa.String(length=128), nullable=False),
    sa.Column('description_key', sa.String(length=512), nullable=False),
    sa.Column('selected_category_code', sa.String(length=16), nullable=False),
    sa.Column('source_transaction_id', sa.String(length=32), nullable=False),
    sa.Column('source_review_decision_id', sa.String(length=32), nullable=False),
    sa.Column('match_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_review_decision_id'], ['review_decisions.id'], ),
    sa.ForeignKeyConstraint(['source_transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('correction_memory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_correction_memory_description_key'), ['description_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_correction_memory_merchant_key'), ['merchant_key'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('correction_memory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_correction_memory_merchant_key'))
        batch_op.drop_index(batch_op.f('ix_correction_memory_description_key'))

    op.drop_table('correction_memory')
    with op.batch_alter_table('category_mapping_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_mapping_entries_profile_id'))

    op.drop_table('category_mapping_entries')
    with op.batch_alter_table('review_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_decisions_transaction_id'))

    op.drop_table('review_decisions')
    with op.batch_alter_table('category_mapping_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_mapping_profiles_business_id'))

    op.drop_table('category_mapping_profiles')
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_tenant_id'))

    op.drop_table('memberships')
    with op.batch_alter_table('categorization_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categorization_results_transaction_id'))

    op.drop_table('categorization_results')
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_businesses_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_businesses_slug'))

    op.drop_table('businesses')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('transactions')
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_slug'))

    op.drop_table('tenants')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_events_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_created_at'))

    op.drop_table('audit_events')
    op.drop_table('account_categories')
    # ### end Alembic commands ###
