"""category mapping editable + source + notes

Revision ID: 527984084a01
Revises: 15d9df38c0b3
Create Date: 2026-05-24 16:18:46.264853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '527984084a01'
down_revision: Union[str, Sequence[str], None] = '15d9df38c0b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_mapping_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.String(length=512), nullable=True))
        batch_op.alter_column('category_code',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)

    with op.batch_alter_table('category_mapping_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=16), server_default='seed', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category_mapping_profiles', schema=None) as batch_op:
        batch_op.drop_column('source')

    with op.batch_alter_table('category_mapping_entries', schema=None) as batch_op:
        batch_op.alter_column('category_code',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
