"""business_id on core workflow tables

Revision ID: 5d5603a94bf4
Revises: 02a42e24f8cd
Create Date: 2026-05-24 19:34:20.852854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d5603a94bf4'
down_revision: Union[str, Sequence[str], None] = '02a42e24f8cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorization_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_categorization_results_business_id'), ['business_id'], unique=False)

    with op.batch_alter_table('correction_memory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_correction_memory_business_id'), ['business_id'], unique=False)

    with op.batch_alter_table('review_decisions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_review_decisions_business_id'), ['business_id'], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_id', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_transactions_business_id'), ['business_id'], unique=False)

    # ### end Alembic commands ###

    # Demo-only backfill: every existing row on an upgraded DB
    # belongs to the single seeded demo workspace by construction
    # (the public deploy has only ever had one business). Attach
    # those rows to the seeded Granite State Auto Repair business
    # so the new business-scoped queries can find them.
    #
    # On a fresh DB the `businesses` table is empty at this point
    # (the seed runs at app startup, after migrations) and the
    # UPDATEs are no-ops — exactly what we want.
    op.execute(
        """
        UPDATE transactions
        SET business_id = (
            SELECT id FROM businesses
            WHERE slug = 'granite-state-auto-repair'
            LIMIT 1
        )
        WHERE business_id IS NULL
          AND EXISTS (
            SELECT 1 FROM businesses
            WHERE slug = 'granite-state-auto-repair'
          )
        """
    )
    op.execute(
        """
        UPDATE categorization_results
        SET business_id = (
            SELECT id FROM businesses
            WHERE slug = 'granite-state-auto-repair'
            LIMIT 1
        )
        WHERE business_id IS NULL
          AND EXISTS (
            SELECT 1 FROM businesses
            WHERE slug = 'granite-state-auto-repair'
          )
        """
    )
    op.execute(
        """
        UPDATE review_decisions
        SET business_id = (
            SELECT id FROM businesses
            WHERE slug = 'granite-state-auto-repair'
            LIMIT 1
        )
        WHERE business_id IS NULL
          AND EXISTS (
            SELECT 1 FROM businesses
            WHERE slug = 'granite-state-auto-repair'
          )
        """
    )
    op.execute(
        """
        UPDATE correction_memory
        SET business_id = (
            SELECT id FROM businesses
            WHERE slug = 'granite-state-auto-repair'
            LIMIT 1
        )
        WHERE business_id IS NULL
          AND EXISTS (
            SELECT 1 FROM businesses
            WHERE slug = 'granite-state-auto-repair'
          )
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_business_id'))
        batch_op.drop_column('business_id')

    with op.batch_alter_table('review_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_decisions_business_id'))
        batch_op.drop_column('business_id')

    with op.batch_alter_table('correction_memory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_correction_memory_business_id'))
        batch_op.drop_column('business_id')

    with op.batch_alter_table('categorization_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categorization_results_business_id'))
        batch_op.drop_column('business_id')

    # ### end Alembic commands ###
