"""csv import profiles

Revision ID: cc70b95bb129
Revises: 527984084a01
Create Date: 2026-05-24 18:26:52.025323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc70b95bb129'
down_revision: Union[str, Sequence[str], None] = '527984084a01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csv_import_profiles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=16), server_default='user', nullable=False),
    sa.Column('amount_mode', sa.String(length=16), nullable=False),
    sa.Column('date_column', sa.String(length=64), nullable=False),
    sa.Column('description_column', sa.String(length=64), nullable=False),
    sa.Column('amount_column', sa.String(length=64), nullable=True),
    sa.Column('debit_column', sa.String(length=64), nullable=True),
    sa.Column('credit_column', sa.String(length=64), nullable=True),
    sa.Column('merchant_column', sa.String(length=64), nullable=True),
    sa.Column('account_column', sa.String(length=64), nullable=True),
    sa.Column('memo_column', sa.String(length=64), nullable=True),
    sa.Column('reference_column', sa.String(length=64), nullable=True),
    sa.Column('expected_headers_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'name', name='uq_csv_import_profiles_business_name')
    )
    with op.batch_alter_table('csv_import_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_csv_import_profiles_business_id'), ['business_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('csv_import_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_csv_import_profiles_business_id'))

    op.drop_table('csv_import_profiles')
    # ### end Alembic commands ###
